### ISSUE TITLE
packaging

### ISSUE THREAD

**Issue by laszewsk** [peterhudec/foundation-sphinx-theme#1]
I stumbled across this theme and was wondering if you could package it similar to how the sphinx bootstrap theme is packaged and host it on pypi?

This would probably make it easier to install. For some reason it failed when I tried using it and installing it by hand. bootstrap and rtfd work just fine for me, but unfortunately I seem to make a mistake somewhere. 

Maybe sphinx has changed since you last worked on it?

**Comment by peterhudec** [comment]
Yes, it definitely could be packaged, but at the time I was starting it, I new little about packaging.
And yes, Sphinx has changed since and the theme currently works with Sphinx<=1.1.3.
Even Foundation has evolved to 5.

There are lots of things to do
